# Generated by Django 4.2.6 on 2023-10-29 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_order',
            name='order',
        ),
        migrations.RemoveField(
            model_name='product_order',
            name='product',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Product_Order',
        ),
    ]
