# Generated by Django 4.2.6 on 2023-10-24 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart_products',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
