# Generated by Django 4.2.6 on 2023-10-24 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_cart_products_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart_products',
            name='total',
        ),
    ]
