# Generated by Django 4.2.6 on 2023-10-21 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_myuser_address'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Images',
            new_name='Image',
        ),
    ]
