# Generated by Django 4.2.6 on 2023-10-24 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_cart_products_total'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WishList_products',
            new_name='Wish_products',
        ),
        migrations.AlterModelOptions(
            name='cart_products',
            options={'ordering': ['products__time_added']},
        ),
    ]
