# Generated by Django 4.2.6 on 2023-10-26 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_rename_wishlist_products_wish_products_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wish_products',
            options={'ordering': ['products__time_added']},
        ),
        migrations.AlterField(
            model_name='wish_products',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
