# Generated by Django 4.2.6 on 2023-10-26 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_wish_products_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart_products',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
